// Code generated by bpf2go; DO NOT EDIT.
//go:build mips || mips64 || ppc64 || s390x

package coreelf

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type BpfBasePacket struct {
	_             structs.HostLayout
	Len           uint16
	ChecksumCount uint8
	Pad           uint8
	Data          [2048]uint8
}

type BpfChecksumMeta struct {
	_              structs.HostLayout
	CsumType       uint8
	Pad            uint8
	CsumOffset     uint16
	HeaderStart    uint16
	HeaderLen      uint16
	IpHeaderOffset uint16
	Pad2           uint16
}

type BpfDatarec struct {
	_              structs.HostLayout
	Packets        uint64
	Bytes          uint64
	DiffErrors     uint64
	ChecksumErrors uint64
}

type BpfDiffEntry struct {
	_          structs.HostLayout
	BaseIdx    uint8
	DiffCount  uint8
	PktLen     uint16
	LenChanged uint8
	Pad        [3]uint8
	Diffs      [8]struct {
		_        structs.HostLayout
		Offset   uint16
		Size     uint8
		Pad      uint8
		OldValue uint32
		NewValue uint32
	}
}

type BpfPktState struct {
	_     structs.HostLayout
	Count uint32
	Idx   uint32
}

// LoadBpf returns the embedded CollectionSpec for Bpf.
func LoadBpf() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_BpfBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load Bpf: %w", err)
	}

	return spec, err
}

// LoadBpfObjects loads Bpf and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*BpfObjects
//	*BpfPrograms
//	*BpfMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func LoadBpfObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := LoadBpf()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// BpfSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type BpfSpecs struct {
	BpfProgramSpecs
	BpfMapSpecs
	BpfVariableSpecs
}

// BpfProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type BpfProgramSpecs struct {
	XdpPassDummy *ebpf.ProgramSpec `ebpf:"xdp_pass_dummy"`
	XdpRx        *ebpf.ProgramSpec `ebpf:"xdp_rx"`
	XdpTx        *ebpf.ProgramSpec `ebpf:"xdp_tx"`
}

// BpfMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type BpfMapSpecs struct {
	BasePacketMap   *ebpf.MapSpec `ebpf:"base_packet_map"`
	ChecksumMetaMap *ebpf.MapSpec `ebpf:"checksum_meta_map"`
	DiffMap         *ebpf.MapSpec `ebpf:"diff_map"`
	PktStateMap     *ebpf.MapSpec `ebpf:"pkt_state_map"`
	RxStatsMap      *ebpf.MapSpec `ebpf:"rx_stats_map"`
	TxStatsMap      *ebpf.MapSpec `ebpf:"tx_stats_map"`
	XdpcapHook      *ebpf.MapSpec `ebpf:"xdpcap_hook"`
}

// BpfVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type BpfVariableSpecs struct {
	EnableXdpcap *ebpf.VariableSpec `ebpf:"enable_xdpcap"`
	SwapResp     *ebpf.VariableSpec `ebpf:"swap_resp"`
}

// BpfObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to LoadBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type BpfObjects struct {
	BpfPrograms
	BpfMaps
	BpfVariables
}

func (o *BpfObjects) Close() error {
	return _BpfClose(
		&o.BpfPrograms,
		&o.BpfMaps,
	)
}

// BpfMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to LoadBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type BpfMaps struct {
	BasePacketMap   *ebpf.Map `ebpf:"base_packet_map"`
	ChecksumMetaMap *ebpf.Map `ebpf:"checksum_meta_map"`
	DiffMap         *ebpf.Map `ebpf:"diff_map"`
	PktStateMap     *ebpf.Map `ebpf:"pkt_state_map"`
	RxStatsMap      *ebpf.Map `ebpf:"rx_stats_map"`
	TxStatsMap      *ebpf.Map `ebpf:"tx_stats_map"`
	XdpcapHook      *ebpf.Map `ebpf:"xdpcap_hook"`
}

func (m *BpfMaps) Close() error {
	return _BpfClose(
		m.BasePacketMap,
		m.ChecksumMetaMap,
		m.DiffMap,
		m.PktStateMap,
		m.RxStatsMap,
		m.TxStatsMap,
		m.XdpcapHook,
	)
}

// BpfVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to LoadBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type BpfVariables struct {
	EnableXdpcap *ebpf.Variable `ebpf:"enable_xdpcap"`
	SwapResp     *ebpf.Variable `ebpf:"swap_resp"`
}

// BpfPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to LoadBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type BpfPrograms struct {
	XdpPassDummy *ebpf.Program `ebpf:"xdp_pass_dummy"`
	XdpRx        *ebpf.Program `ebpf:"xdp_rx"`
	XdpTx        *ebpf.Program `ebpf:"xdp_tx"`
}

func (p *BpfPrograms) Close() error {
	return _BpfClose(
		p.XdpPassDummy,
		p.XdpRx,
		p.XdpTx,
	)
}

func _BpfClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed bpf_bpfeb.o
var _BpfBytes []byte
