// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64 || wasm

package coreelf

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type BpfBasePacket struct {
	_             structs.HostLayout
	Len           uint16
	ChecksumCount uint8
	Pad           uint8
	Data          [2048]uint8
}

type BpfChecksumMeta struct {
	_              structs.HostLayout
	CsumOffset     uint16
	HeaderStart    uint16
	HeaderLen      uint16
	IpHeaderOffset uint16
	IpVersion      uint8
	IpProtocol     uint8
}

type BpfDatarec struct {
	_              structs.HostLayout
	Packets        uint64
	Bytes          uint64
	DiffErrors     uint64
	ChecksumErrors uint64
}

type BpfDiffEntry struct {
	_     structs.HostLayout
	Diffs [8]struct {
		_           structs.HostLayout
		OldValue    [8]uint8
		NewValue    [8]uint8
		Offset      uint16
		Size        uint8
		AffectsCsum uint8
	}
	PktLen     uint16
	BaseIdx    uint8
	DiffCount  uint8
	LenChanged uint8
	CsumCached uint8
}

type BpfPktState struct {
	_           structs.HostLayout
	Count       uint32
	Idx         uint32
	LastBaseIdx uint32
}

type BpfTailCallCtx struct {
	_              structs.HostLayout
	BaseIdx        uint32
	LocalIdx       uint32
	TargetLen      uint16
	DiffCount      uint8
	ChecksumCount  uint8
	LenChanged     uint8
	DiffErrors     uint8
	ChecksumErrors uint8
	Pad            [1]uint8
}

// LoadBpf returns the embedded CollectionSpec for Bpf.
func LoadBpf() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_BpfBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load Bpf: %w", err)
	}

	return spec, err
}

// LoadBpfObjects loads Bpf and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*BpfObjects
//	*BpfPrograms
//	*BpfMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func LoadBpfObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := LoadBpf()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// BpfSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type BpfSpecs struct {
	BpfProgramSpecs
	BpfMapSpecs
	BpfVariableSpecs
}

// BpfProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type BpfProgramSpecs struct {
	XdpPassDummy    *ebpf.ProgramSpec `ebpf:"xdp_pass_dummy"`
	XdpRx           *ebpf.ProgramSpec `ebpf:"xdp_rx"`
	XdpTx           *ebpf.ProgramSpec `ebpf:"xdp_tx"`
	XdpTxChecksum   *ebpf.ProgramSpec `ebpf:"xdp_tx_checksum"`
	XdpTxCsumDiff   *ebpf.ProgramSpec `ebpf:"xdp_tx_csum_diff"`
	XdpTxCsumRecalc *ebpf.ProgramSpec `ebpf:"xdp_tx_csum_recalc"`
}

// BpfMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type BpfMapSpecs struct {
	BasePacketMap   *ebpf.MapSpec `ebpf:"base_packet_map"`
	ChecksumMetaMap *ebpf.MapSpec `ebpf:"checksum_meta_map"`
	DiffMap         *ebpf.MapSpec `ebpf:"diff_map"`
	PktStateMap     *ebpf.MapSpec `ebpf:"pkt_state_map"`
	RxStatsMap      *ebpf.MapSpec `ebpf:"rx_stats_map"`
	TailCallCtxMap  *ebpf.MapSpec `ebpf:"tail_call_ctx_map"`
	TxStatsMap      *ebpf.MapSpec `ebpf:"tx_stats_map"`
	XdpProgs        *ebpf.MapSpec `ebpf:"xdp_progs"`
}

// BpfVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type BpfVariableSpecs struct {
	MaxBasePackets     *ebpf.VariableSpec `ebpf:"max_base_packets"`
	MaxChecksumEntries *ebpf.VariableSpec `ebpf:"max_checksum_entries"`
	MaxDiffsPerPacket  *ebpf.VariableSpec `ebpf:"max_diffs_per_packet"`
	MaxPacketSize      *ebpf.VariableSpec `ebpf:"max_packet_size"`
	MinPacketSize      *ebpf.VariableSpec `ebpf:"min_packet_size"`
	SwapResp           *ebpf.VariableSpec `ebpf:"swap_resp"`
}

// BpfObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to LoadBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type BpfObjects struct {
	BpfPrograms
	BpfMaps
	BpfVariables
}

func (o *BpfObjects) Close() error {
	return _BpfClose(
		&o.BpfPrograms,
		&o.BpfMaps,
	)
}

// BpfMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to LoadBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type BpfMaps struct {
	BasePacketMap   *ebpf.Map `ebpf:"base_packet_map"`
	ChecksumMetaMap *ebpf.Map `ebpf:"checksum_meta_map"`
	DiffMap         *ebpf.Map `ebpf:"diff_map"`
	PktStateMap     *ebpf.Map `ebpf:"pkt_state_map"`
	RxStatsMap      *ebpf.Map `ebpf:"rx_stats_map"`
	TailCallCtxMap  *ebpf.Map `ebpf:"tail_call_ctx_map"`
	TxStatsMap      *ebpf.Map `ebpf:"tx_stats_map"`
	XdpProgs        *ebpf.Map `ebpf:"xdp_progs"`
}

func (m *BpfMaps) Close() error {
	return _BpfClose(
		m.BasePacketMap,
		m.ChecksumMetaMap,
		m.DiffMap,
		m.PktStateMap,
		m.RxStatsMap,
		m.TailCallCtxMap,
		m.TxStatsMap,
		m.XdpProgs,
	)
}

// BpfVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to LoadBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type BpfVariables struct {
	MaxBasePackets     *ebpf.Variable `ebpf:"max_base_packets"`
	MaxChecksumEntries *ebpf.Variable `ebpf:"max_checksum_entries"`
	MaxDiffsPerPacket  *ebpf.Variable `ebpf:"max_diffs_per_packet"`
	MaxPacketSize      *ebpf.Variable `ebpf:"max_packet_size"`
	MinPacketSize      *ebpf.Variable `ebpf:"min_packet_size"`
	SwapResp           *ebpf.Variable `ebpf:"swap_resp"`
}

// BpfPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to LoadBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type BpfPrograms struct {
	XdpPassDummy    *ebpf.Program `ebpf:"xdp_pass_dummy"`
	XdpRx           *ebpf.Program `ebpf:"xdp_rx"`
	XdpTx           *ebpf.Program `ebpf:"xdp_tx"`
	XdpTxChecksum   *ebpf.Program `ebpf:"xdp_tx_checksum"`
	XdpTxCsumDiff   *ebpf.Program `ebpf:"xdp_tx_csum_diff"`
	XdpTxCsumRecalc *ebpf.Program `ebpf:"xdp_tx_csum_recalc"`
}

func (p *BpfPrograms) Close() error {
	return _BpfClose(
		p.XdpPassDummy,
		p.XdpRx,
		p.XdpTx,
		p.XdpTxChecksum,
		p.XdpTxCsumDiff,
		p.XdpTxCsumRecalc,
	)
}

func _BpfClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed bpf_bpfel.o
var _BpfBytes []byte
