// Code generated by bpf2go; DO NOT EDIT.
//go:build mips || mips64 || ppc64 || s390x

package scx

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

// LoadScx returns the embedded CollectionSpec for Scx.
func LoadScx() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_ScxBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load Scx: %w", err)
	}

	return spec, err
}

// LoadScxObjects loads Scx and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*ScxObjects
//	*ScxPrograms
//	*ScxMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func LoadScxObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := LoadScx()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// ScxSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type ScxSpecs struct {
	ScxProgramSpecs
	ScxMapSpecs
	ScxVariableSpecs
}

// ScxProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type ScxProgramSpecs struct {
	XdperfDispatch  *ebpf.ProgramSpec `ebpf:"xdperf_dispatch"`
	XdperfEnqueue   *ebpf.ProgramSpec `ebpf:"xdperf_enqueue"`
	XdperfExit      *ebpf.ProgramSpec `ebpf:"xdperf_exit"`
	XdperfInit      *ebpf.ProgramSpec `ebpf:"xdperf_init"`
	XdperfSelectCpu *ebpf.ProgramSpec `ebpf:"xdperf_select_cpu"`
}

// ScxMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type ScxMapSpecs struct {
	ExitInfo   *ebpf.MapSpec `ebpf:"exit_info"`
	WorkerTids *ebpf.MapSpec `ebpf:"worker_tids"`
	XdperfOps  *ebpf.MapSpec `ebpf:"xdperf_ops"`
}

// ScxVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type ScxVariableSpecs struct {
	WorkerCpuMask *ebpf.VariableSpec `ebpf:"worker_cpu_mask"`
	XdperfTgid    *ebpf.VariableSpec `ebpf:"xdperf_tgid"`
}

// ScxObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to LoadScxObjects or ebpf.CollectionSpec.LoadAndAssign.
type ScxObjects struct {
	ScxPrograms
	ScxMaps
	ScxVariables
}

func (o *ScxObjects) Close() error {
	return _ScxClose(
		&o.ScxPrograms,
		&o.ScxMaps,
	)
}

// ScxMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to LoadScxObjects or ebpf.CollectionSpec.LoadAndAssign.
type ScxMaps struct {
	ExitInfo   *ebpf.Map `ebpf:"exit_info"`
	WorkerTids *ebpf.Map `ebpf:"worker_tids"`
	XdperfOps  *ebpf.Map `ebpf:"xdperf_ops"`
}

func (m *ScxMaps) Close() error {
	return _ScxClose(
		m.ExitInfo,
		m.WorkerTids,
		m.XdperfOps,
	)
}

// ScxVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to LoadScxObjects or ebpf.CollectionSpec.LoadAndAssign.
type ScxVariables struct {
	WorkerCpuMask *ebpf.Variable `ebpf:"worker_cpu_mask"`
	XdperfTgid    *ebpf.Variable `ebpf:"xdperf_tgid"`
}

// ScxPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to LoadScxObjects or ebpf.CollectionSpec.LoadAndAssign.
type ScxPrograms struct {
	XdperfDispatch  *ebpf.Program `ebpf:"xdperf_dispatch"`
	XdperfEnqueue   *ebpf.Program `ebpf:"xdperf_enqueue"`
	XdperfExit      *ebpf.Program `ebpf:"xdperf_exit"`
	XdperfInit      *ebpf.Program `ebpf:"xdperf_init"`
	XdperfSelectCpu *ebpf.Program `ebpf:"xdperf_select_cpu"`
}

func (p *ScxPrograms) Close() error {
	return _ScxClose(
		p.XdperfDispatch,
		p.XdperfEnqueue,
		p.XdperfExit,
		p.XdperfInit,
		p.XdperfSelectCpu,
	)
}

func _ScxClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed scx_bpfeb.o
var _ScxBytes []byte
